# Project information
site_name: Citrix Federated Authentication Service 2003 PowerShell cmdlets
site_description: Citrix Federated Authentication Service 2003 PowerShell cmdlets Reference
site_title: Developer Docs
site_url: https://developer-docs.citrix.com


# Copyright
copyright: 'Copyright &copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: https://citrix.com/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'

# Page tree
nav:
- Citrix Federated Authentication Service PowerShell cmdlets:
    - Introduction: index.md
- cmdlets reference:
  - Get-FasAdministrationPolicy: Get-FasAdministrationPolicy.md
  - Get-FasAuthorizationCertificate: Get-FasAuthorizationCertificate.md
  - Get-FasCertificateDefinition: Get-FasCertificateDefinition.md
  - Get-FasCloudConfig: Get-FasCloudConfig.md
  - Get-FasMsCertificateAuthority: Get-FasMsCertificateAuthority.md
  - Get-FasMsTemplate: Get-FasMsTemplate.md
  - Get-FasPolicyOid: Get-FasPolicyOid.md
  - Get-FasPrivateKeyPoolInfo: Get-FasPrivateKeyPoolInfo.md
  - Get-FasRule: Get-FasRule.md
  - Get-FasServer: Get-FasServer.md
  - Get-FasServerForUser: Get-FasServerForUser.md
  - Get-FasUserCertificate: Get-FasUserCertificate.md
  - Import-FasAuthorizationCertificateResponse: Import-FasAuthorizationCertificateResponse.md
  - New-FasAuthorizationCertificate: New-FasAuthorizationCertificate.md
  - New-FasAuthorizationCertificateRequest: New-FasAuthorizationCertificateRequest.md
  - New-FasCertificateDefinition: New-FasCertificateDefinition.md
  - New-FasCloudConfig: New-FasCloudConfig.md
  - New-FasMsTemplate: New-FasMsTemplate.md
  - New-FasPolicyOid: New-FasPolicyOid.md
  - New-FasRule: New-FasRule.md
  - New-FasUserCertificate: New-FasUserCertificate.md
  - Publish-FasMsTemplate: Publish-FasMsTemplate.md
  - Remove-FasAuthorizationCertificate: Remove-FasAuthorizationCertificate.md
  - Remove-FasCertificateDefinition: Remove-FasCertificateDefinition.md
  - Remove-FasCloudConfig: Remove-FasCloudConfig.md
  - Remove-FasMsTemplate: Remove-FasMsTemplate.md
  - Remove-FasPolicyOid: Remove-FasPolicyOid.md
  - Remove-FasRule: Remove-FasRule.md
  - Remove-FasUserCertificate: Remove-FasUserCertificate.md
  - Set-FasAdministrationPolicy: Set-FasAdministrationPolicy.md
  - Set-FasCertificateDefinition: Set-FasCertificateDefinition.md
  - Set-FasCloudConfig: Set-FasCloudConfig.md
  - Set-FasPolicyOid: Set-FasPolicyOid.md
  - Set-FasRule: Set-FasRule.md
  - Set-FasServer: Set-FasServer.md
  - Test-FasCertificateSigningRequest: Test-FasCertificateSigningRequest.md
  - Test-FasCrypto: Test-FasCrypto.md
  - Test-FasKeyPairCreation: Test-FasKeyPairCreation.md
  - Test-FasUserCertificateCrypto: Test-FasUserCertificateCrypto.md
  - Unpublish-FasMsTemplate: Unpublish-FasMsTemplate.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/
